userInfo:
  name: lixin
  age: 26 
  sex: male
  height: 173cm
  weight: 70kg
  hobbies: 户外、音乐、电游
spring:
  datasource:
    username: lixin
    password: '{cipher}AQAoWqtSuiPH3qypw3CrRIu5jZOKJhIukbmPLJTGYNQ3FwbuM+oKKNLrrRHY8+XLc+6f+zzGt3Yxjiiuv+sMXlxTptmqIAEaW2SvPUsKq84q53OjOsBHZEagi/pcMIAknUshcDW7/ihvn05ya1uKMDNQECLlNpJKfZmTTPn/h7U8EKzYkmE1K9i5duSGC2J6tPKV0jrFG1mZqUdcXfcbJzyqEnTfsF79w4HfnwYvzM01Kd+bXCpywHBIp37emPzWCQGLbqo0mWW1SWQKHmnOj8yLreAGLTwRENCYbbUzt1C+IbdSc+a8R+4IjxxdzLAQ27mmr/zn51SpujEkSAq3HSIXfV9uPC7x1JQK/3reUmCnLEPEdns0GJ7AwCvXM4j1h1k='


